package:
  name: openalea.vpltk
  version: 2.0.1

source:
  path: ..

build:
  preserve_egg_dir: True
  script: python setup.py install --prefix=$PREFIX
  build_number : 1


requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools

test:
  imports:
    - openalea.vpltk

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License