{% set data = load_setup_py_data() %}

package:
  name: openalea.vpltk
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  script: {{PYTHON}} setup.py install
  number : 0


requirements:
  build:
    - python {{PY_VER}}
    - setuptools
    - openalea.deploy
    - six
  run:
    - python >=3.6
    - setuptools
    - pyqt >=5
    - qtconsole
    - openalea.core

test:
  imports:
    - openalea.vpltk

about:
  home: {{ data.get('url') }}
  license: Cecill-C License
  summary: {{ data.get('description') }}
